services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bootiful'
      - 'POSTGRES_PASSWORD=bootiful'
      - 'POSTGRES_USER=bootiful'
    ports:
      - '5432:5432'

  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411:9411'